dubailap/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView
from product import views

#creat a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/product/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

product/urls.py
from django.conf.urls import patterns, url
from product import views

urlpatterns = patterns('',
       url(r'^$', views.index, name='index'),
       url(r'^product_page/(?P<product_id>\d+)/$', views.product_page, name='prdocut_page'),
       url(r'^categories/$', views.categories, name='categories'),
       url(r'^category/(?P<cat_name_slug>[-\w]+)/$', views.category_page, name='category'),
       url(r'^brands/$', views.brands, name='brands'),
       url(r'^brand/(?P<brand_name_slug>[-\w]+)/$', views.brand_page, name='brand_page'),
       url(r'^price/(?P<price_pattern>[-\w]+)/$', views.price, name='price'),
       url(r'^customer_contact/$', views.ps_contact, name='price'),

       )

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.template.defaultfilters import slugify
import os
import datetime
from django.core.validators import RegexValidator

# Create your models here.

### STORAGE ###

pi = FileSystemStorage(location='/media/product_images')
ci = FileSystemStorage(location='/media/category_icons')

### FILE / IMAGE UPLOAD FUNCTIONS ###

def update_Product_image_filename(instance, filename):
    ctime = datetime.datetime.now()
    ctime_string = ctime.strftime("%Y%m%d%H%M%S")
    path = "product_images"
    basename , extension = os.path.splitext(filename)
    format = "dubailap_" + ctime_string + extension
    return os.path.join(path, format)


def update_cat_icon_filename(instance, filename):
    ctime = datetime.datetime.now()
    ctime_string = ctime.strftime("%Y%m%d%H%M%S")
    path = "category_icons"
    basename , extension = os.path.splitext(filename)
    format = "cat_icon_" + ctime_string + extension
    return os.path.join(path, format)


def update_brand_icon_filename(instance, filename):
    ctime = datetime.datetime.now()
    ctime_string = ctime.strftime("%Y%m%d%H%M%S")
    path = "brand_icons"
    basename , extension = os.path.splitext(filename)
    format = "brand_icon_" + ctime_string + extension
    return os.path.join(path, format)


### MODELS ###

class Category(models.Model):
    category_name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    category_icon = models.ImageField(upload_to=update_cat_icon_filename)

        # Override th __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)


class Brand(models.Model):
    brand_name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    brand_icon = models.ImageField(upload_to=update_brand_icon_filename)

        # Override th __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.brand_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.brand_name)
        super(Brand, self).save(*args, **kwargs)



class ProductProfile(models.Model):
    category = models.ForeignKey(Category)
    brand = models.ForeignKey(Brand)
    product_name = models.CharField(max_length=128)
    model_name = models.CharField(max_length=128)
    generation = models.CharField(max_length=128)
    processor = models.CharField(max_length=128)
    ram = models.DecimalField(max_digits=2, decimal_places=0)
    hdd = models.DecimalField(max_digits=6, decimal_places=2)
    optical_drive = models.CharField(max_length=128)
    display = models.CharField(max_length=128)
    card_reader = models.CharField(max_length=128)
    blue_tooth = models.CharField(max_length=128)
    web_cam = models.CharField(max_length=128)
    warranty = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    condition = models.TextField()
    product_image = models.ImageField(upload_to=update_Product_image_filename)
    post_date = models.DateTimeField(db_index=True, auto_now_add=True)

    # Override th __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.product_name



class UserProfile(models.Model):
    # This line is required.Links Userprofile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override th __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username



class Customer_ps_contact(models.Model):
    name = models.CharField(max_length=128, help_text="Name")
    email = models.EmailField(max_length=75, help_text="Email")
    subject = models.CharField(max_length=128,help_text="Subject" )
    product = models.ForeignKey(ProductProfile, help_text="Product")
    message = models.TextField(help_text="Message")
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=15, help_text="Phone Number") # validators should be a list

    def __unicode__(self):
        return self.name

product/forms.py
from django import forms
from django.contrib.auth.models import User
from product.models import ProductProfile, Customer_ps_contact



class Customer_ps_contactForm(forms.ModelForm):

    class Meta:
        model = Customer_ps_contact
        fields = ('name','email','subject','product', 'message', 'phone_number')

product/views.py
from django.core.mail import send_mail
from django.shortcuts import render

from product.forms import Customer_ps_contactForm
from product.models import ProductProfile, Category, Brand


# Create your views here.


def home(request):
    products = ProductProfile.objects.all()
    context_dict = {'products': products}
    response = render(request,'home.html', context_dict)
    return response

def index (request):
    context_dict = {}
    context_dict['abc'] = 'We are here'
    return render(request, 'product/index.html', context_dict)


def about (request):
    context_dict = {}
    context_dict['abc'] = 'We are here'
    return render(request, 'product/about.html', context_dict)


def contact (request):
    context_dict = {}
    context_dict['abc'] = 'We are here'
    return render(request, 'product/contact.html', context_dict)



def product_page(request, product_id):
    product = ProductProfile.objects.get(pk=product_id)
    context_dict = {'product': product}
    response = render(request,'product/product_page.html', context_dict)
    return response


def categories(request):
    category = Category.objects.all()
    context_dict = {'cat': category}
    response = render(request,'product/categories.html', context_dict)
    return response


def category_page(request, cat_name_slug):
    cat = Category.objects.get(slug=cat_name_slug)
    context_dict = {}
    products = ProductProfile.objects.filter(category=cat)
    context_dict['category'] = cat
    context_dict['products'] = products
    response = render(request,'product/category_page.html', context_dict)
    return response



def brands(request):
    brands = Brand.objects.all()
    context_dict = {'brands': brands}
    response = render(request,'product/brands.html', context_dict)
    return response


def brand_page(request, brand_name_slug):
    brand = Brand.objects.get(slug=brand_name_slug)
    context_dict = {}
    products = ProductProfile.objects.filter(brand=brand)
    context_dict['brand'] = brand
    context_dict['products'] = products
    response = render(request,'product/brand_page.html', context_dict)
    return response





def price(request, price_pattern):
    sorted_price_wise = ""
    price_pattern_heading = ""
    if price_pattern == 'low-high':
        pp = 'price'
        price_pattern_heading = "Price (Lowest ~ Highest)"
        sorted_price_wise  = ProductProfile.objects.all().order_by(pp)
    elif price_pattern == 'high-low':
        pp = '-price'
        price_pattern_heading = "Price (Highest ~ Lowest)"
        sorted_price_wise  = ProductProfile.objects.all().order_by(pp)
    else:
        pass

    context_dict = {'products': sorted_price_wise, 'price_pattern_heading': price_pattern_heading}
    response = render(request,'product/price.html', context_dict)
    return response


def mail_customer_enquriy(form_data_dict):
    name=form_data_dict['name']
    email=form_data_dict['email']
    subject=form_data_dict['subject']
    formatted_subject = "Enquiry @ Dubi Lap: "+subject
    product=form_data_dict['product']
    product_name = product.product_name
    message=form_data_dict['message']
    phone_number=form_data_dict['phone_number']
    formatted_message = "Dear Admin,\n\nYou have recived an Enquiry Regarding "+product_name+" with following particulars:\n\nName: "+name+"\nEmail: "+email+"\nSubject: "+subject+"\nPhone No.: "+phone_number+"\nInterested In: "+product_name+"\n\nMessage:\n\n"+message

    send_mail(formatted_subject,
              formatted_message,
              'enquriy.dubailap@gmail.com',
              ['pleasureinblues@gmail.com'],
              fail_silently=False)


def thank_u_customer(form_data_dict):
    name=form_data_dict['name']
    email=form_data_dict['email']
    subject= "Dubi Lap | Thank you for Enquiry"
    formatted_message = "Dear "+name+",\n\nThank you for your enquiry.\n\nOne of our representative will contact you soon.\n\nWe hope to have long-term relationship with you.\n\n\nRegards,\n\nDubiLap\nwww.dubilap.com"

    send_mail(subject,
              formatted_message,
              'enquriy.dubailap@gmail.com',
              [email],
              fail_silently=False)

def ps_contact(request):
    if request.method == 'POST':
        form = Customer_ps_contactForm(request.POST)

        if form.is_valid():
            form_data_dict = form.cleaned_data
            mail_customer_enquriy(form_data_dict)
            thank_u_customer(form_data_dict)

            form.save(commit=True)
            return home(request)
        else:
            print (form.errors)
    else:
        form = Customer_ps_contactForm()

    return render(request, 'product/contact_form.html', {'form':form})


def handler404(request):
    response = render('404.html', {'context_instace':request})
    response.status_code = 404
    return response

templates/product/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}
{% block title %}About Us{% endblock %}

{% block body_block %}<!-- body Block starts here -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
            <li><a href="{% url 'home' %}">Home</a>
        </li>
        <li>
            <a href="#">About Us</a>
        </li>
    </ol>

</div>


<br><br><br>

<div class="row panel panel-purple">

            <div class="panel-heading">About Dubi Lap </div>
                <div class=" panel-body col-xs-8 col-md-12">

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at elit fringilla, pharetra arcu vel, consectetur odio. Phasellus gravida ligula et ante posuere, nec rutrum tellus bibendum. In eu aliquam metus. Fusce ultricies ex ac dui consequat, eget bibendum mi feugiat. Nunc vestibulum lectus sed efficitur tincidunt. Duis sagittis arcu ut pulvinar imperdiet. Curabitur libero nulla, dictum quis gravida nec, cursus nec erat. Aliquam iaculis nisl sed vehicula hendrerit.
</p>
<p>
Integer id lacus nec mi commodo sodales. Integer interdum tellus quis semper convallis. Vestibulum libero ex, ultricies in dapibus ac, ultrices in risus. Nulla eget feugiat justo. Vivamus quis quam eget lectus gravida mollis non sit amet ante. Praesent sed metus vitae enim tincidunt aliquet. Cras vel auctor felis, in vestibulum dui. Etiam congue sit amet turpis at laoreet. Pellentesque sed blandit lorem, vitae egestas nulla. Etiam elementum turpis ac augue vehicula, vitae molestie ipsum condimentum. Integer consectetur commodo ex et porta. Curabitur faucibus ex nec augue dictum maximus. Nulla convallis ultrices purus, vitae egestas sapien sodales nec. Nullam aliquet ligula sit amet sem hendrerit iaculis.
</p>
<p>
Quisque sollicitudin lorem enim, et dignissim metus ullamcorper mattis. Praesent congue ligula mauris, vitae lacinia enim eleifend quis. In laoreet sem odio, non aliquam nisl sollicitudin ut. Vivamus fringilla quam at tellus luctus, auctor tristique nisi iaculis. Morbi ut nisl iaculis, dictum elit ac, sollicitudin lectus. Praesent et tellus metus. Ut elementum convallis lectus sit amet placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec quis dapibus eros, vel ullamcorper arcu.
</p>
<p>
Praesent tortor est, pellentesque non sem in, varius tincidunt est. Phasellus id placerat lacus, id consequat velit. Praesent elementum, sapien in faucibus volutpat, risus purus facilisis magna, non dictum sapien metus sed felis. Ut metus lorem, vulputate in maximus sit amet, lobortis ut ligula. Donec at dolor ut ante mattis sodales. Fusce elementum odio vitae urna tempor, ut convallis mauris maximus. Pellentesque et ante sagittis, facilisis turpis ut, semper ex. Donec id pretium metus. Nullam tempus imperdiet lorem, vitae tempor mi ultrices ac. Nulla facilisi. Pellentesque maximus rutrum ex, ut sagittis nulla aliquet in. Suspendisse cursus, turpis sit amet ornare accumsan, mauris neque lacinia nisi, et maximus nisl lectus id ante. Nam convallis sem sed nisl tincidunt tristique. Fusce sed nibh sed lorem viverra ultricies et vitae nibh. Nunc volutpat tempor est et suscipit. Sed et augue in nunc dapibus consequat.
</p>
<p>
Phasellus quis orci at augue cursus posuere faucibus quis quam. Ut quis ipsum sit amet felis commodo efficitur non et tortor. Cras ornare euismod magna id condimentum. Mauris ornare turpis elementum tortor finibus semper. Nullam vestibulum dignissim turpis, vitae consectetur ipsum pellentesque sit amet. Pellentesque pretium nunc et lacinia facilisis. Cras molestie dignissim mauris, id gravida felis luctus et. Phasellus posuere quis ligula et finibus. Praesent vel dui tempor elit tristique elementum. Sed id felis tempus, rhoncus orci at, lacinia velit. In a dignissim odio. Nullam aliquet porta fermentum. Aliquam in lectus at ante fermentum suscipit. In hac habitasse platea dictumst. Fusce ac mattis arcu.
</p>
<p>
Phasellus ac ultrices ex. Aliquam sed mollis risus. Cras quis arcu vitae nibh elementum viverra. Morbi a velit sit amet odio dictum pulvinar in et quam. Vivamus fringilla pretium nisi sed hendrerit. Nulla at ex id neque cursus dignissim. Pellentesque porttitor velit ante, sed fringilla purus commodo nec. Pellentesque non laoreet elit. Nullam iaculis ultricies erat, nec aliquet lorem tincidunt auctor. Proin imperdiet nisl sit amet ipsum euismod rutrum. Phasellus vulputate ultricies malesuada. Duis risus nisi, vehicula vel nisl a, semper consectetur sem. Pellentesque porta congue dui vitae egestas.
</p>

                </div>
            <div class="col-xs-8 col-md-6">
            </div>

                </div>







{% endblock %}

templates/product/brand_list.html
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
data-position="right" class="navbar-default navbar-static-side">
<div class="sidebar-collapse menu-scroll">

    {% if brand %}

    <div id="side-menu" class="nav">


        <div class="sidebar-collapse menu-scroll">
            <ul id="side-menu" class="nav">
                <div class="clearfix"></div>



<li>
    <a href="{% url 'home' %}"><i class="fa fa-home fa-2x">&nbsp;&nbsp;</i>Home</a>
</li>

                <li>
    <a href="{% url 'about' %}"><i class="fa fa-user fa-x2">&nbsp;&nbsp;</i>About Us</a>
</li>

                <li>
    <a href="{% url 'contact' %}"><i class="fa fa-phone fa-x2">&nbsp;&nbsp;</i>Contact Us</a>
</li>
               <div style="background-color:#488c6c; color:#fff; padding-left:5px; margin:0;"><p><span class="glyphicons glyphicons-search"><i>Search by Brands</i></span></p></div>
                {% for b in brand %}

                {% if b == act_brand %}

                <li  class="active" >
                    {% else  %}
                    <li>
                        {% endif %}
                        <a href="{% url 'product:brand_page'  b.slug %}">
                            <img src="/media/{{b.brand_icon}}" class="img-rounded" alt="{{ b.brand_name}}" width="36" height="36"/>
                            <span class="menu-title">{{b.brand_name}} </span>
                        </a>
                    </li>
                    {% endfor %}
                  <div style="background-color:#488c6c; color:#fff; padding-left:5px; margin:0;"><p><i>Search by Price</i></p></div>
                <li><a href="{% url 'product:price' 'high-low' %}"> <span><i class="fa fa-angle-down fa-x2">&nbsp;&nbsp;</i> Price (Highest ~ Lowest)</span></a></li>
                <li><a href="{% url 'product:price' 'low-high' %}"> <span><i class="fa fa-angle-up fa-x2">&nbsp;&nbsp;</i> Price (Lowest ~ Highest)</span></a></li>


                    {% else %}
                    <li>
                        <strong >There are no category present.</strong>
                    </li>


                </ul>
                {% endif %}



            </div>
        </nav>
    <!--

-->

templates/product/brand_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ brand.brand_name }}{% endblock %}

{% block body_block %}
<!-- body Block starts here -->

<!-- Breadcrumb -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
        <li>
            <a href="index.html">Home</a>
        </li>
        <li>
            <a href="">Brand</a>
        </li>
        <li>
            <a href="#">{{ brand.brand_name }}</a>
        </li>
    </ol>
</div>
<br><br><br>

<!-- Cateogry Details -->
<div class="panel-body">
    <img src="{{ MEDIA_URL }}{{brand.brand_icon}}" class="img-rounded pull-left"
         alt="{{ brand.brand_name}}" width="10%" height="10%"/>
    <h2 style="margin-left:15px" class="pull-left">{{ brand.brand_name }}</h2>
</div>

{% if brand %}
    {% if products %}
    {% for p in products %}

        <div class="row panel panel-purple">

            <div class="panel-heading">{{ p.product_name }}</div>
                <div class=" panel-body col-xs-8 col-md-6">
                    <table class="table table-hover">
                        <tr>
                            <td width="165px">Product Name</td>
                            <td>
                                <strong>{{p.product_name }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Brand Name</td>
                            <td>
                                <strong>{{p.brand }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Model</td>
                            <td>
                                <strong>{{p.model_name }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Generation</td>
                            <td>
                                <strong>{{p.generation }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Processor</td>
                            <td>
                                <strong>{{p.processor }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>RAM</td>
                            <td>
                                <strong>{{p.ram }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Display</td>
                            <td>
                                <strong>{{p.display }}</strong>
                            </td>
                        </tr>
                    </table>

                </div>
            <div class="col-xs-8 col-md-6">
                <img src="{{ MEDIA_URL }}{{p.product_image}}" class="img-rounded center-block"
                 alt="{{ p.product_name}}" width="60%" height="60%"/>
                <p class="text-center">{{p.product_name }}</p>
                <hr>
            </div>
            <div style="padding-bottom:10px;" class ="col-md-12">
         <a href="/product/product_page/{{p.id}}">
                    <button type="button" class="btn btn-danger pull-right">Check out Details</button>
             </a>

            </div>
                </div>


    {% endfor %}
    {% else %}
        <p class="unav">No product found in category : {{category}} </p>
    {% endif %}

{% else %}
    <strong>No such category.</strong>
{% endif %}


{% endblock %}

templates/product/brands.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ product.brand_name }}{% endblock %}

{% block body_block %}<!-- body Block starts here -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
            <li><a href="index.html">Home</a>
        </li>
        <li>
            <a href="#">Categories</a>
        </li>

    </ol>

</div>
<br><br><br>
<div class="panel panel-purple">
    <div class="panel-heading">Main Brands</div>
    <a class="panel-body">


    {% for brand in brands %}
    {% if brand %}


            <a href="{% url 'product:brand_page' brand.slug %}">
        <div class="panel">
            <div class="panel-body">
                <h3 style="margin:0 auto; valign:middle;"> {{ brand.brand_name }}</h3>
                    <img style="margin:0 auto; valign:middle;" src="{{MEDIA_URL}}{{brand.brand_icon}}" class="img-rounded center-block" alt="{{ brand.brand_name}}"/>
            </div>
        </div>
        </a>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
    {% endfor %}

</div>
</div>






{% endblock %}

templates/product/categories.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ product.product_name }}{% endblock %}

{% block body_block %}<!-- body Block starts here -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
            <li><a href="index.html">Home</a>
        </li>
        <li>
            <a href="#">Categories</a>
        </li>

    </ol>

</div>
<br><br><br>
<div class="panel panel-purple">
    <div class="panel-heading">Categories</div>
    <a class="panel-body">


    {% for category in cat %}
    {% if category %}


            <a href="{% url 'product:category' category.slug %}">
        <div class="panel">
            <div class="panel-body">
                <h3 style="margin:0 auto; valign:middle;"> {{ category.category_name }}</h3>
                    <img style="margin:0 auto; valign:middle;" src="{{ MEDIA_URL }}{{category.category_icon}}" class="img-rounded center-block" alt="{{ category.category_name}}"/>
            </div>
        </div>
        </a>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
    {% endfor %}

</div>
</div>






{% endblock %}

templates/product/category_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ product.product_name }}{% endblock %}

{% block body_block %}
<!-- body Block starts here -->

<!-- Breadcrumb -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
        <li>
            <a href="index.html">Home</a>
        </li>
        <li>
            <a href="">Category</a>
        </li>
        <li>
            <a href="#">{{ category.category_name }}</a>
        </li>
    </ol>
</div>
<br><br><br>

<!-- Cateogry Details -->
<div class="panel-body">
    <img src="{{ MEDIA_URL }}{{category.category_icon}}" class="img-rounded pull-left"
         alt="{{ category.category_name}}" width="10%" height="10%"/>
    <h2 style="margin-left:15px" class="pull-left">{{ category.category_name }}</h2>
</div>

{% if category %}
    {% if products %}
    {% for p in products %}

        <div class="row panel panel-purple">

            <div class="panel-heading">{{ p.product_name }}</div>
                <div class=" panel-body col-xs-8 col-md-6">
                    <table class="table table-hover">
                        <tr>
                            <td width="165px">Product Name</td>
                            <td>
                                <strong>{{p.product_name }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Brand Name</td>
                            <td>
                                <strong>{{p.brand }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Model</td>
                            <td>
                                <strong>{{p.model_name }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Generation</td>
                            <td>
                                <strong>{{p.generation }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Processor</td>
                            <td>
                                <strong>{{p.processor }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>RAM</td>
                            <td>
                                <strong>{{p.ram }}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td>Display</td>
                            <td>
                                <strong>{{p.display }}</strong>
                            </td>
                        </tr>
                    </table>

                </div>
            <div class="col-xs-8 col-md-6">
                <img src="{{ MEDIA_URL }}{{p.product_image}}" class="img-rounded center-block"
                 alt="{{ p.product_name}}" width="60%" height="60%"/>
                <p class="text-center">{{p.product_name }}</p>
                <hr>
            </div>
            <div style="padding-bottom:10px;" class ="col-md-12">
         <a href="/product/product_page/{{p.id}}">
                    <button type="button" class="btn btn-danger pull-right">Check out Details</button>
             </a>

            </div>
                </div>


    {% endfor %}
    {% else %}
        <p class="unav">No product found in category : {{category}} </p>
    {% endif %}

{% else %}
    <strong>No such category.</strong>
{% endif %}


{% endblock %}

templates/product/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}
{% block title %}Contact Us{% endblock %}

{% block body_block %}<!-- body Block starts here -->
<div>
    <ol class="breadcrumb page-breadcrumbs pull-left">
            <li><a href="{% url 'home' %}">Home</a>
        </li>
        <li>
            <a href="#">Contact Us</a>
        </li>
    </ol>

</div>


<br><br><br>

<div class="panel panel-brown">
  <div class="panel-heading">
    Contacts Form
  </div>
  <div class="panel-body pan">
    <form action="#">
      <div class="form-body pal">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="inputName" class="control-label">
                Name
              </label>
              <div class="input-icon right">
                <i class="fa fa-user">
                </i>
                <input id="inputName" type="text" placeholder="" class="form-control">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="inputEmail" class="control-label">
                E-mail
              </label>
              <div class="input-icon right">
                <i class="fa fa-envelope">
                </i>
                <input id="inputEmail" type="text" placeholder="" class="form-control">
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="inputSubject" class="control-label">
            Subject
          </label>
          <div class="input-icon right">
            <i class="fa fa-tag">
            </i>
            <input id="inputSubject" type="text" placeholder="" class="form-control">
          </div>
        </div>
        <div class="form-group">
          <label for="inputMessage" class="control-label">
            Message
          </label>
          <textarea rows="5" class="form-control">
          </textarea>
        </div>
        <div class="form-group mbn">
          <div class="checkbox">
            <label class="">
              <div class="icheckbox_minimal-grey" style="position: relative;">
                <input tabindex="5" type="checkbox" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                <ins class="iCheck-helper" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                </ins>
              </div>
              &nbsp; Send a copy to my e-mail address
            </label>
          </div>
        </div>
      </div>
      <div class="form-actions text-right pal">
        <button type="submit" class="btn btn-primary">
          Send message
        </button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

templates/product/index.html
{% load staticfiles %}

Product Index

{{ abc }}